Revert "Don't have spellcheck action fail"
This reverts commit 13338188ab535431e41de593adff5c5d833ed64f.

diff --git a/.github/workflows/spellcheck.yml b/.github/workflows/spellcheck.yml
--- a/.github/workflows/spellcheck.yml
+++ b/.github/workflows/spellcheck.yml
@@ -66,3 +66,10 @@ jobs:
           labels: |
             OpenScPCA admin
             spelling
+
+      - name: Fail if there are spelling errors
+        if: steps.spell.outputs.error_count > 0
+        run: |
+          echo "There were ${{ steps.spell.outputs.error_count }} errors"
+          column -t spell_check_errors.tsv
+          exit 1
